"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("KeyWords", [
      {
        type: "mainRole",
        key: "MROLE0",
        viValue: "Quản trị viên",
        enValue: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "mainRole",
        key: "MROLE1",
        viValue: "Quản lí",
        enValue: "Manager",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "mainRole",
        key: "MROLE2",
        viValue: "Trưởng phòng",
        enValue: "Leader",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "mainRole",
        key: "MROLE3",
        viValue: "Nhân viên",
        enValue: "Staff",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "subRole",
        key: "SROLE0",
        viValue: "Không có",
        enValue: "Not yet",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "subRole",
        key: "SROLE1",
        viValue: "Quản lí",
        enValue: "Manager",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "subRole",
        key: "SROLE2",
        viValue: "Trưởng phòng",
        enValue: "Leader",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "subRole",
        key: "SROLE3",
        viValue: "Lập trình viên",
        enValue: "Deverloper",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "subRole",
        key: "SROLE4",
        viValue: "Kiểm thử viên",
        enValue: "Tester",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "subRole",
        key: "SROLE5",
        viValue: "Phân tích, kinh doanh",
        enValue: "Business Analyst",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "subRole",
        key: "SROLE6",
        viValue: "Quản lý phần cứng",
        enValue: "Hardware Manager",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "subRole",
        key: "SROLE7",
        viValue: "Thiết kế CSDL",
        enValue: "Databases Manager",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "subRole",
        key: "SROLE8",
        viValue: "Nhân viên sản xuất",
        enValue: "Production staff",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "subRole",
        key: "SROLE9",
        viValue: "Bộ phận khác",
        enValue: "Other",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "workType",
        key: "WType0",
        viValue: "Thời gian cơ bản",
        enValue: "Basic time work",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "workType",
        key: "WType1",
        viValue: "Làm thêm 2 tiếng",
        enValue: "2hr overtime",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "workType",
        key: "WType2",
        viValue: "Làm thêm 4 tiếng",
        enValue: "4hr overtime",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "dayType",
        key: "DType0",
        viValue: "Ngày thường",
        enValue: "Normal day",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "dayType",
        key: "DType1",
        viValue: "Chủ nhật",
        enValue: "Sunday bonus",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "dayType",
        key: "DType2",
        viValue: "Ngày lễ",
        enValue: "Holiday bonus",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("KeyWords", null, {});
  },
};
